# Site settings
title: Acjx
username: jianxinzhou
email: zhoujx0219@163.com
description: "Succinctly"
url: "http://jianxinzhou.github.io"
baseurl: ""

markdown: kramdown
permalink: /:title

comments :
    provider : duoshuo
    duoshuo : 
      short_name : jianxinzhou

sass:
  sass_dir: public/css
  style: :compressed
